xwayland {
  force_zero_scaling = true
}

device {
    name = mouse-passthrough
    natural_scroll = true
    scroll_factor = 5.0
}

device {
    name = mouse-passthrough-(absolute)
    natural_scroll = true
    scroll_factor = 5.0
}

device {
    name = unknown-device
    natural_scroll = true
    scroll_factor = 5.0
}

# Caelestia whiteboard rules
# windowrule = workspace special:whiteboard, match:title Caelestia Whiteboard
windowrule = float true, match:title Caelestia Whiteboard
windowrule = size 600 450, match:title Caelestia Whiteboard
windowrule = move 68 460, match:title Caelestia Whiteboard












