-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

hl.config({
    xwayland = {
        force_zero_scaling = true,
    },
})

hl.device({
    name = "mouse-passthrough",
    natural_scroll = true,
    scroll_factor = 5.0,
})

hl.device({
    name = "mouse-passthrough-(absolute)",
    natural_scroll = true,
    scroll_factor = 5.0,
})

hl.device({
    name = "unknown-device",
    natural_scroll = true,
    scroll_factor = 5.0,
})

-- Caelestia whiteboard rules

hl.window_rule({
    name  = "float_true",
    match = {
        title = "Caelestia Whiteboard",
    },
    float = true,
})
