-- Generated by Antigravity
---@module 'hl'

-- Add hyprland subdirectory to package path
_G.hypr = os.getenv("HOME") .. "/.config/hypr"
local hypr_dir = _G.hypr
package.path = package.path .. ";" .. hypr_dir .. "/hyprland/?.lua"

-- Helper to load variables from a .conf file
local function load_conf_vars(filepath)
    local vars = {}
    local file = io.open(filepath, "r")
    if not file then return vars end
    for line in file:lines() do
        local name, val = line:match("^%s*%$(%w+)%s*=%s*([^#]+)")
        if name and val then
            vars[name] = val:gsub("%s+$", "") -- trim trailing whitespace
        end
    end
    file:close()
    return vars
end

-- Load colors from current.conf (fallback to default.conf)
local colors = load_conf_vars(hypr_dir .. "/scheme/current.conf")
if not next(colors) then
    colors = load_conf_vars(hypr_dir .. "/scheme/default.conf")
end

-- Export base colors to _G
for k, v in pairs(colors) do
    _G[k] = v
end

-- Set metatable on _G for dynamic alpha-suffixed color variables
setmetatable(_G, {
    __index = function(t, key)
        local base, alpha = key:match("^(%a+)(%x%x)$")
        if base and alpha and colors[base] then
            return colors[base] .. alpha
        end
        return nil
    end
})

-- Copy default.conf to current.conf if not exists (runs on reload/startup)
hl.on("config.reloaded", function()
    hl.exec_cmd("cp -L --no-preserve=mode --update=none " .. hypr_dir .. "/scheme/default.conf " .. hypr_dir .. "/scheme/current.conf")
    hl.exec_cmd(hypr_dir .. "/scripts/configs.sh ~/.config/caelestia")
end)

-- Default monitor conf
hl.monitor({
    output   = "",
    mode     = "preferred",
    position = "auto",
    scale    = 1.25,
})

-- Autostart
hl.on("hyprland.start", function()
    hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
end)

-- Load variables and export to _G
local vars = require("variables")
for k, v in pairs(vars) do
    _G[k] = v
end

-- Load user variables
local cConf = os.getenv("HOME") .. "/.config/caelestia"
local ok_vars, err_vars = pcall(dofile, cConf .. "/hypr-vars.lua")
if not ok_vars then
    print("Warning: could not load hypr-vars.lua:", err_vars)
end

-- Load sub-configs
require("env")
require("general")
require("input")
require("misc")
require("animations")
require("decoration")
require("group")
require("execs")
require("rules")
require("gestures")
require("keybinds")
require("scrolling")

-- Load user overrides
local ok_user, err_user = pcall(dofile, cConf .. "/hypr-user.lua")
if not ok_user then
    print("Warning: could not load hypr-user.lua:", err_user)
end
