-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- ### Hyprland ###

-- Apps

local terminal = "kitty"

local browser = "vivaldi"

local editor = "code"

local fileExplorer = "thunar"

-- Touchpad

local touchpadDisableTyping = true

local touchpadScrollFactor = 0.3

local workspaceSwipeFingers = 4

local gestureFingers = 3

local gestureFingersMore = 4

-- Blur

local blurEnabled = true

local blurSpecialWs = false

local blurPopups = true

local blurInputMethods = true

local blurSize = 8

local blurPasses = 2

local blurXray = false

-- Shadow

local shadowEnabled = true

local shadowRange = 20

local shadowRenderPower = 3

local shadowColour = "rgba(" .. surfaced4 .. ")"

-- Gaps

local workspaceGaps = 20

local windowGapsIn = 5

local windowGapsOut = 10

local singleWindowGapsOut = 20

-- Window styling

local windowOpacity = 0.95

local windowRounding = 15

local windowBorderSize = 1

local activeWindowBorderColour = "rgba(" .. primarye6 .. ")"

local inactiveWindowBorderColour = "rgba(" .. onSurfaceVariant11 .. ")"

-- Misc

local volumeStep = 10

-- In percent

local cursorTheme = "macOS"

local cursorSize = 34

-- ### Keybinds ###

-- Workspaces

local kbMoveWinToWs = "Super+Alt"

local kbMoveWinToWsGroup = "Ctrl+Super+Alt"

local kbGoToWs = "Super"

local kbGoToWsGroup = "Ctrl+Super"

local kbNextWs = "Ctrl+Super,right"

local kbPrevWs = "Ctrl+Super,left"

local kbToggleSpecialWs = "Super,S"

-- Window groups

local kbWindowGroupCycleNext = "Alt,Tab"

local kbWindowGroupCyclePrev = "Shift+Alt,Tab"

local kbUngroup = "Super,U"

local kbToggleGroup = "Super,Comma"

-- Window actions

local kbMoveWindow = "Super,Z"

local kbResizeWindow = "Super,X"

local kbWindowPip = "Super+Alt,Backslash"

local kbPinWindow = "Super,P"

local kbWindowFullscreen = "Super,F"

local kbWindowBorderedFullscreen = "Super+Alt,F"

local kbToggleWindowFloating = "Super+Alt,Space"

local kbCloseWindow = "Super,Q"

-- Special workspace toggles

local kbSystemMonitor = "Ctrl+Shift,Escape"

local kbMusic = "Super,M"

local kbCommunication = "Super,D"

local kbTodo = "Super,R"

-- Apps

local kbTerminal = "Super,T"

local kbBrowser = "Super,B"

local kbEditor = "Super,C"

local kbFileExplorer = "Super,E"

-- Misc

local kbSession = "Ctrl+Alt,Delete"

local kbShowSidebar = "Super,N"

local kbClearNotifs = "Ctrl+Alt,C"

local kbShowPanels = "Super,K"

local kbLock = "Super,L"

local kbRestoreLock = "Super+Alt,L"

return {
    terminal = terminal,
    browser = browser,
    editor = editor,
    fileExplorer = fileExplorer,
    touchpadDisableTyping = touchpadDisableTyping,
    touchpadScrollFactor = touchpadScrollFactor,
    workspaceSwipeFingers = workspaceSwipeFingers,
    gestureFingers = gestureFingers,
    gestureFingersMore = gestureFingersMore,
    blurEnabled = blurEnabled,
    blurSpecialWs = blurSpecialWs,
    blurPopups = blurPopups,
    blurInputMethods = blurInputMethods,
    blurSize = blurSize,
    blurPasses = blurPasses,
    blurXray = blurXray,
    shadowEnabled = shadowEnabled,
    shadowRange = shadowRange,
    shadowRenderPower = shadowRenderPower,
    shadowColour = shadowColour,
    workspaceGaps = workspaceGaps,
    windowGapsIn = windowGapsIn,
    windowGapsOut = windowGapsOut,
    singleWindowGapsOut = singleWindowGapsOut,
    windowOpacity = windowOpacity,
    windowRounding = windowRounding,
    windowBorderSize = windowBorderSize,
    activeWindowBorderColour = activeWindowBorderColour,
    inactiveWindowBorderColour = inactiveWindowBorderColour,
    volumeStep = volumeStep,
    cursorTheme = cursorTheme,
    cursorSize = cursorSize,
    kbMoveWinToWs = kbMoveWinToWs,
    kbMoveWinToWsGroup = kbMoveWinToWsGroup,
    kbGoToWs = kbGoToWs,
    kbGoToWsGroup = kbGoToWsGroup,
    kbNextWs = kbNextWs,
    kbPrevWs = kbPrevWs,
    kbToggleSpecialWs = kbToggleSpecialWs,
    kbWindowGroupCycleNext = kbWindowGroupCycleNext,
    kbWindowGroupCyclePrev = kbWindowGroupCyclePrev,
    kbUngroup = kbUngroup,
    kbToggleGroup = kbToggleGroup,
    kbMoveWindow = kbMoveWindow,
    kbResizeWindow = kbResizeWindow,
    kbWindowPip = kbWindowPip,
    kbPinWindow = kbPinWindow,
    kbWindowFullscreen = kbWindowFullscreen,
    kbWindowBorderedFullscreen = kbWindowBorderedFullscreen,
    kbToggleWindowFloating = kbToggleWindowFloating,
    kbCloseWindow = kbCloseWindow,
    kbSystemMonitor = kbSystemMonitor,
    kbMusic = kbMusic,
    kbCommunication = kbCommunication,
    kbTodo = kbTodo,
    kbTerminal = kbTerminal,
    kbBrowser = kbBrowser,
    kbEditor = kbEditor,
    kbFileExplorer = kbFileExplorer,
    kbSession = kbSession,
    kbShowSidebar = kbShowSidebar,
    kbClearNotifs = kbClearNotifs,
    kbShowPanels = kbShowPanels,
    kbLock = kbLock,
    kbRestoreLock = kbRestoreLock,
}
