-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- ### Hyprland ###

-- Apps

local terminal = "kitty"

local browser = "vivaldi"

local editor = "code"

local fileExplorer = "thunar"

-- Touchpad

local touchpadDisableTyping = true

local touchpadScrollFactor = 0.3

local workspaceSwipeFingers = 4

local gestureFingers = 3

local gestureFingersMore = 4

-- Blur

local blurEnabled = true

local blurSpecialWs = false

local blurPopups = true

local blurInputMethods = true

local blurSize = 8

local blurPasses = 2

local blurXray = false

-- Shadow

local shadowEnabled = true

local shadowRange = 20

local shadowRenderPower = 3

local shadowColour = "rgba(" .. surfaced4 .. ")"

-- Gaps

local workspaceGaps = 20

local windowGapsIn = 5

local windowGapsOut = 10

local singleWindowGapsOut = 20

-- Window styling

local windowOpacity = 0.95

local windowRounding = 15

local windowBorderSize = 1

local activeWindowBorderColour = "rgba(" .. primarye6 .. ")"

local inactiveWindowBorderColour = "rgba(" .. onSurfaceVariant11 .. ")"

-- Misc

local volumeStep = 10

-- In percent

local cursorTheme = "macOS"

local cursorSize = 34

-- ### Keybinds ###

-- Workspaces

local kbMoveWinToWs = "SUPER+ALT"

local kbMoveWinToWsGroup = "CTRL+SUPER+ALT"

local kbGoToWs = "SUPER"

local kbGoToWsGroup = "CTRL+SUPER"

local kbNextWs = "CTRL+SUPER,right"

local kbPrevWs = "CTRL+SUPER,left"

local kbToggleSpecialWs = "SUPER,S"

-- Window groups

local kbWindowGroupCycleNext = "ALT,Tab"

local kbWindowGroupCyclePrev = "SHIFT+ALT,Tab"

local kbUngroup = "SUPER,U"

local kbToggleGroup = "SUPER,Comma"

-- Window actions

local kbMoveWindow = "SUPER,Z"

local kbResizeWindow = "SUPER,X"

local kbWindowPip = "SUPER+ALT,Backslash"

local kbPinWindow = "SUPER,P"

local kbWindowFullscreen = "SUPER,F"

local kbWindowBorderedFullscreen = "SUPER+ALT,F"

local kbToggleWindowFloating = "SUPER+ALT,Space"

local kbCloseWindow = "SUPER,Q"

-- Special workspace toggles

local kbSystemMonitor = "CTRL+SHIFT,Escape"

local kbMusic = "SUPER,M"

local kbCommunication = "SUPER,D"

local kbTodo = "SUPER,R"

-- Apps

local kbTerminal = "SUPER,T"

local kbBrowser = "SUPER,B"

local kbEditor = "SUPER,C"

local kbFileExplorer = "SUPER,E"

-- Misc

local kbSession = "CTRL+ALT,Delete"

local kbShowSidebar = "SUPER,N"

local kbClearNotifs = "CTRL+ALT,C"

local kbShowPanels = "SUPER,K"

local kbLock = "SUPER,L"

local kbRestoreLock = "SUPER+ALT,L"

return {
    terminal = terminal,
    browser = browser,
    editor = editor,
    fileExplorer = fileExplorer,
    touchpadDisableTyping = touchpadDisableTyping,
    touchpadScrollFactor = touchpadScrollFactor,
    workspaceSwipeFingers = workspaceSwipeFingers,
    gestureFingers = gestureFingers,
    gestureFingersMore = gestureFingersMore,
    blurEnabled = blurEnabled,
    blurSpecialWs = blurSpecialWs,
    blurPopups = blurPopups,
    blurInputMethods = blurInputMethods,
    blurSize = blurSize,
    blurPasses = blurPasses,
    blurXray = blurXray,
    shadowEnabled = shadowEnabled,
    shadowRange = shadowRange,
    shadowRenderPower = shadowRenderPower,
    shadowColour = shadowColour,
    workspaceGaps = workspaceGaps,
    windowGapsIn = windowGapsIn,
    windowGapsOut = windowGapsOut,
    singleWindowGapsOut = singleWindowGapsOut,
    windowOpacity = windowOpacity,
    windowRounding = windowRounding,
    windowBorderSize = windowBorderSize,
    activeWindowBorderColour = activeWindowBorderColour,
    inactiveWindowBorderColour = inactiveWindowBorderColour,
    volumeStep = volumeStep,
    cursorTheme = cursorTheme,
    cursorSize = cursorSize,
    kbMoveWinToWs = kbMoveWinToWs,
    kbMoveWinToWsGroup = kbMoveWinToWsGroup,
    kbGoToWs = kbGoToWs,
    kbGoToWsGroup = kbGoToWsGroup,
    kbNextWs = kbNextWs,
    kbPrevWs = kbPrevWs,
    kbToggleSpecialWs = kbToggleSpecialWs,
    kbWindowGroupCycleNext = kbWindowGroupCycleNext,
    kbWindowGroupCyclePrev = kbWindowGroupCyclePrev,
    kbUngroup = kbUngroup,
    kbToggleGroup = kbToggleGroup,
    kbMoveWindow = kbMoveWindow,
    kbResizeWindow = kbResizeWindow,
    kbWindowPip = kbWindowPip,
    kbPinWindow = kbPinWindow,
    kbWindowFullscreen = kbWindowFullscreen,
    kbWindowBorderedFullscreen = kbWindowBorderedFullscreen,
    kbToggleWindowFloating = kbToggleWindowFloating,
    kbCloseWindow = kbCloseWindow,
    kbSystemMonitor = kbSystemMonitor,
    kbMusic = kbMusic,
    kbCommunication = kbCommunication,
    kbTodo = kbTodo,
    kbTerminal = kbTerminal,
    kbBrowser = kbBrowser,
    kbEditor = kbEditor,
    kbFileExplorer = kbFileExplorer,
    kbSession = kbSession,
    kbShowSidebar = kbShowSidebar,
    kbClearNotifs = kbClearNotifs,
    kbShowPanels = kbShowPanels,
    kbLock = kbLock,
    kbRestoreLock = kbRestoreLock,
}
