-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

hl.config({
    decoration = {
        rounding = windowRounding,
        blur = {
            enabled = blurEnabled,
            xray = blurXray,
            special = blurSpecialWs,
            ignore_opacity = true,
            -- Allows opacity blurring
            new_optimizations = true,
            popups = blurPopups,
            input_methods = blurInputMethods,
            size = blurSize,
            passes = blurPasses,
        },
        shadow = {
            enabled = shadowEnabled,
            range = shadowRange,
            render_power = shadowRenderPower,
            color = shadowColour,
        },
    },
})
