-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- ############# Themes #############

hl.env("QT_QPA_PLATFORMTHEME", "qtengine")

hl.env("QT_WAYLAND_DISABLE_WINDOWDECORATION", 1)

hl.env("QT_AUTO_SCREEN_SCALE_FACTOR", 1)

hl.env("XCURSOR_THEME", cursorTheme)

hl.env("XCURSOR_SIZE", cursorSize)

-- ######## Toolkit backends ########

hl.env("GDK_BACKEND", "wayland,x11")

hl.env("QT_QPA_PLATFORM", "wayland;xcb")

hl.env("SDL_VIDEODRIVER", "wayland,x11,windows")

hl.env("CLUTTER_BACKEND", "wayland")

hl.env("ELECTRON_OZONE_PLATFORM_HINT", "auto")

-- ####### XDG specifications #######

hl.env("XDG_CURRENT_DESKTOP", "Hyprland")

hl.env("XDG_SESSION_TYPE", "wayland")

hl.env("XDG_SESSION_DESKTOP", "Hyprland")

-- ############# Others #############

hl.env("_JAVA_AWT_WM_NONREPARENTING", 1)
