-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

hl.config({
    general = {
        layout = "dwindle",
        allow_tearing = false,
        -- Allows `immediate` window rule to work
        gaps_workspaces = workspaceGaps,
        gaps_in = windowGapsIn,
        gaps_out = windowGapsOut,
        border_size = windowBorderSize,
        col = {
            active_border = activeWindowBorderColour,
            inactive_border = inactiveWindowBorderColour,
        },
    },
})

hl.config({
    dwindle = {
        preserve_split = true,
        smart_split = false,
        smart_resizing = true,
    },
})
