-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

hl.config({
    gestures = {
        workspace_swipe_distance = 700,
        workspace_swipe_cancel_ratio = 0.15,
        workspace_swipe_min_speed_to_force = 5,
        workspace_swipe_direction_lock = true,
        workspace_swipe_direction_lock_threshold = 10,
        workspace_swipe_create_new = true,
    },
})

-- TODO: manual review: gesture = workspaceSwipeFingers, "horizontal", "workspace"

-- TODO: manual review: gesture = gestureFingers, "up", "special", "special"

-- TODO: manual review: gesture = gestureFingers, "down", "dispatcher", "exec", "caelestia toggle specialws"

-- TODO: manual review: gesture = gestureFingersMore, "down", "dispatcher", "exec", "systemctl suspend-then-hibernate"
