-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

hl.config({
    group = {
        groupbar = {
            font_family = "JetBrains Mono NF",
            font_size = 15,
            gradients = true,
            gradient_round_only_edges = false,
            gradient_rounding = 5,
            height = 25,
            indicator_height = 0,
            gaps_in = 3,
            gaps_out = 3,
            text_color = "rgb(" .. onPrimary .. ")",
            ["col.active"] = "rgba(" .. primaryd4 .. ")",
            ["col.inactive"] = "rgba(" .. outlined4 .. ")",
            ["col.locked_active"] = "rgba(" .. primaryd4 .. ")",
            ["col.locked_inactive"] = "rgba(" .. secondaryd4 .. ")",
        },
        col = {
            border_active = activeWindowBorderColour,
            border_inactive = inactiveWindowBorderColour,
            border_locked_active = activeWindowBorderColour,
            border_locked_inactive = inactiveWindowBorderColour,
        },
    },
})
