-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

hl.config({
    input = {
        kb_layout = "es",
        numlock_by_default = false,
        repeat_delay = 250,
        repeat_rate = 35,
        focus_on_close = 1,
        touchpad = {
            natural_scroll = true,
            disable_while_typing = touchpadDisableTyping,
            scroll_factor = touchpadScrollFactor,
        },
    },
})

hl.config({
    binds = {
        scroll_event_delay = 0,
    },
})

hl.config({
    cursor = {
        hotspot_padding = 1,
        no_hardware_cursors = false,
    },
})
