-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'


hl.define_submap("global", function()
    -- ## Shell keybinds
    -- Launcher release bind
    hl.bind("SUPER" .. " + " .. "Super_L", hl.dsp.exec_cmd("caelestia shell drawers toggle launcher"), { release = true })
    hl.bind("SUPER" .. " + " .. 1, hl.dsp.global("caelestia:launcherInterrupt"), { ignore_mods = true, non_consuming = true })
    hl.bind("SUPER" .. " + " .. 2, hl.dsp.global("caelestia:launcherInterrupt"), { ignore_mods = true, non_consuming = true })
    hl.bind("SUPER" .. " + " .. 3, hl.dsp.global("caelestia:launcherInterrupt"), { ignore_mods = true, non_consuming = true })
    hl.bind("SUPER" .. " + " .. 4, hl.dsp.global("caelestia:launcherInterrupt"), { ignore_mods = true, non_consuming = true })
    hl.bind("SUPER" .. " + " .. 5, hl.dsp.global("caelestia:launcherInterrupt"), { ignore_mods = true, non_consuming = true })
    hl.bind("SUPER" .. " + " .. 6, hl.dsp.global("caelestia:launcherInterrupt"), { ignore_mods = true, non_consuming = true })
    hl.bind("SUPER" .. " + " .. 7, hl.dsp.global("caelestia:launcherInterrupt"), { ignore_mods = true, non_consuming = true })
    hl.bind("SUPER" .. " + " .. 8, hl.dsp.global("caelestia:launcherInterrupt"), { ignore_mods = true, non_consuming = true })
    hl.bind("SUPER" .. " + " .. 9, hl.dsp.global("caelestia:launcherInterrupt"), { ignore_mods = true, non_consuming = true })
    hl.bind("SUPER" .. " + " .. 0, hl.dsp.global("caelestia:launcherInterrupt"), { ignore_mods = true, non_consuming = true })
    hl.bind("SUPER" .. " + " .. "S", hl.dsp.global("caelestia:launcherInterrupt"), { ignore_mods = true, non_consuming = true })
    hl.bind("SUPER" .. " + " .. "Z", hl.dsp.global("caelestia:launcherInterrupt"), { ignore_mods = true, non_consuming = true })
    hl.bind("SUPER" .. " + " .. "X", hl.dsp.global("caelestia:launcherInterrupt"), { ignore_mods = true, non_consuming = true })
    hl.bind("SUPER" .. " + " .. "P", hl.dsp.global("caelestia:launcherInterrupt"), { ignore_mods = true, non_consuming = true })
    hl.bind("SUPER" .. " + " .. "F", hl.dsp.global("caelestia:launcherInterrupt"), { ignore_mods = true, non_consuming = true })
    hl.bind("SUPER" .. " + " .. "Q", hl.dsp.global("caelestia:launcherInterrupt"), { ignore_mods = true, non_consuming = true })
    hl.bind("SUPER" .. " + " .. "M", hl.dsp.global("caelestia:launcherInterrupt"), { ignore_mods = true, non_consuming = true })
    hl.bind("SUPER" .. " + " .. "D", hl.dsp.global("caelestia:launcherInterrupt"), { ignore_mods = true, non_consuming = true })
    hl.bind("SUPER" .. " + " .. "H", hl.dsp.global("caelestia:launcherInterrupt"), { ignore_mods = true, non_consuming = true })
    hl.bind("SUPER" .. " + " .. "R", hl.dsp.global("caelestia:launcherInterrupt"), { ignore_mods = true, non_consuming = true })
    hl.bind("SUPER" .. " + " .. "T", hl.dsp.global("caelestia:launcherInterrupt"), { ignore_mods = true, non_consuming = true })
    hl.bind("SUPER" .. " + " .. "B", hl.dsp.global("caelestia:launcherInterrupt"), { ignore_mods = true, non_consuming = true })
    hl.bind("SUPER" .. " + " .. "C", hl.dsp.global("caelestia:launcherInterrupt"), { ignore_mods = true, non_consuming = true })
    hl.bind("SUPER" .. " + " .. "E", hl.dsp.global("caelestia:launcherInterrupt"), { ignore_mods = true, non_consuming = true })
    hl.bind("SUPER" .. " + " .. "N", hl.dsp.global("caelestia:launcherInterrupt"), { ignore_mods = true, non_consuming = true })
    hl.bind("SUPER" .. " + " .. "K", hl.dsp.global("caelestia:launcherInterrupt"), { ignore_mods = true, non_consuming = true })
    hl.bind("SUPER" .. " + " .. "L", hl.dsp.global("caelestia:launcherInterrupt"), { ignore_mods = true, non_consuming = true })
    hl.bind("SUPER" .. " + " .. "V", hl.dsp.global("caelestia:launcherInterrupt"), { ignore_mods = true, non_consuming = true })
    hl.bind("SUPER" .. " + " .. "Period", hl.dsp.global("caelestia:launcherInterrupt"), { ignore_mods = true, non_consuming = true })
    hl.bind("SUPER" .. " + " .. "left", hl.dsp.global("caelestia:launcherInterrupt"), { ignore_mods = true, non_consuming = true })
    hl.bind("SUPER" .. " + " .. "right", hl.dsp.global("caelestia:launcherInterrupt"), { ignore_mods = true, non_consuming = true })
    hl.bind("SUPER" .. " + " .. "up", hl.dsp.global("caelestia:launcherInterrupt"), { ignore_mods = true, non_consuming = true })
    hl.bind("SUPER" .. " + " .. "down", hl.dsp.global("caelestia:launcherInterrupt"), { ignore_mods = true, non_consuming = true })
    hl.bind("SUPER" .. " + " .. "Page_Up", hl.dsp.global("caelestia:launcherInterrupt"), { ignore_mods = true, non_consuming = true })
    hl.bind("SUPER" .. " + " .. "Page_Down", hl.dsp.global("caelestia:launcherInterrupt"), { ignore_mods = true, non_consuming = true })
    -- bindin = Super, mouse_up, global, caelestia:launcherInterrupt
    -- bindin = Super, mouse_down, global, caelestia:launcherInterrupt
    hl.bind("SUPER" .. " + " .. "Space", hl.dsp.global("caelestia:launcherInterrupt"), { ignore_mods = true, non_consuming = true })
    hl.bind("SUPER" .. " + " .. "Backslash", hl.dsp.global("caelestia:launcherInterrupt"), { ignore_mods = true, non_consuming = true })
    hl.bind("SUPER" .. " + " .. "bracketright", hl.dsp.global("caelestia:launcherInterrupt"), { ignore_mods = true, non_consuming = true })
    hl.bind("SUPER" .. " + " .. "braceright", hl.dsp.global("caelestia:launcherInterrupt"), { ignore_mods = true, non_consuming = true })
    hl.bind("SUPER" .. " + " .. "code:35", hl.dsp.global("caelestia:launcherInterrupt"), { ignore_mods = true, non_consuming = true })
    hl.bind("SUPER" .. " + " .. "slash", hl.dsp.global("caelestia:launcherInterrupt"), { ignore_mods = true, non_consuming = true })
    hl.bind("SUPER" .. " + " .. "question", hl.dsp.global("caelestia:launcherInterrupt"), { ignore_mods = true, non_consuming = true })
    hl.bind("SUPER" .. " + " .. "code:61", hl.dsp.global("caelestia:launcherInterrupt"), { ignore_mods = true, non_consuming = true })
    hl.bind("SUPER" .. " + " .. "f12", hl.dsp.global("caelestia:launcherInterrupt"), { ignore_mods = true, non_consuming = true })
    hl.bind("SUPER" .. " + " .. "mouse:274", hl.dsp.global("caelestia:launcherInterrupt"), { ignore_mods = true, non_consuming = true })
    hl.bind("SUPER" .. " + " .. "mouse:275", hl.dsp.global("caelestia:launcherInterrupt"), { ignore_mods = true, non_consuming = true })
    hl.bind("SUPER" .. " + " .. "mouse:276", hl.dsp.global("caelestia:launcherInterrupt"), { ignore_mods = true, non_consuming = true })
    hl.bind("SUPER" .. " + " .. "mouse:277", hl.dsp.global("caelestia:launcherInterrupt"), { ignore_mods = true, non_consuming = true })
    -- Misc
    hl.bind("CTRL+ALT" .. " + " .. "Delete", hl.dsp.global("caelestia:session"))
    hl.bind("SUPER" .. " + " .. "N", hl.dsp.global("caelestia:sidebar"))
    hl.bind("CTRL+ALT" .. " + " .. "C", hl.dsp.global("caelestia:clearNotifs"), { locked = true })
    hl.bind("SUPER" .. " + " .. "K", hl.dsp.global("caelestia:showall"))
    hl.bind("SUPER" .. " + " .. "L", hl.dsp.global("caelestia:lock"))
    -- Restore lock
    hl.bind("SUPER+ALT" .. " + " .. "L", hl.dsp.exec_cmd("caelestia shell -d"), { locked = true })
    hl.bind("SUPER+ALT" .. " + " .. "L", hl.dsp.global("caelestia:lock"), { locked = true })
    -- Brightness
    hl.bind("XF86MonBrightnessUp", hl.dsp.global("caelestia:brightnessUp"), { locked = true })
    hl.bind("XF86MonBrightnessDown", hl.dsp.global("caelestia:brightnessDown"), { locked = true })
    -- Media
    hl.bind("CTRL+SUPER" .. " + " .. "Space", hl.dsp.global("caelestia:mediaToggle"), { locked = true })
    hl.bind("XF86AudioPlay", hl.dsp.global("caelestia:mediaToggle"), { locked = true })
    hl.bind("XF86AudioPause", hl.dsp.global("caelestia:mediaToggle"), { locked = true })
    hl.bind("CTRL+SUPER" .. " + " .. "Equal", hl.dsp.global("caelestia:mediaNext"), { locked = true })
    hl.bind("XF86AudioNext", hl.dsp.global("caelestia:mediaNext"), { locked = true })
    hl.bind("CTRL+SUPER" .. " + " .. "Minus", hl.dsp.global("caelestia:mediaPrev"), { locked = true })
    hl.bind("XF86AudioPrev", hl.dsp.global("caelestia:mediaPrev"), { locked = true })
    hl.bind("XF86AudioStop", hl.dsp.global("caelestia:mediaStop"), { locked = true })
    -- Kill/restart
    hl.bind("CTRL+SUPER+SHIFT" .. " + " .. "R", hl.dsp.exec_cmd("qs -c caelestia kill"), { release = true })
    hl.bind("CTRL+SUPER+ALT" .. " + " .. "R", hl.dsp.exec_cmd("qs -c caelestia kill; sleep . 1; caelestia shell -d"), { release = true })
    -- Go to workspace #
    local wsaction = "~/.config/hypr/scripts/wsaction.sh"
    hl.bind("SUPER" .. " + " .. 1, hl.dsp.exec_cmd("~/.config/hypr/scripts/wsaction.sh workspace 1"))
    hl.bind("SUPER" .. " + " .. 2, hl.dsp.exec_cmd("~/.config/hypr/scripts/wsaction.sh workspace 2"))
    hl.bind("SUPER" .. " + " .. 3, hl.dsp.exec_cmd("~/.config/hypr/scripts/wsaction.sh workspace 3"))
    hl.bind("SUPER" .. " + " .. 4, hl.dsp.exec_cmd("~/.config/hypr/scripts/wsaction.sh workspace 4"))
    hl.bind("SUPER" .. " + " .. 5, hl.dsp.exec_cmd("~/.config/hypr/scripts/wsaction.sh workspace 5"))
    hl.bind("SUPER" .. " + " .. 6, hl.dsp.exec_cmd("~/.config/hypr/scripts/wsaction.sh workspace 6"))
    hl.bind("SUPER" .. " + " .. 7, hl.dsp.exec_cmd("~/.config/hypr/scripts/wsaction.sh workspace 7"))
    hl.bind("SUPER" .. " + " .. 8, hl.dsp.exec_cmd("~/.config/hypr/scripts/wsaction.sh workspace 8"))
    hl.bind("SUPER" .. " + " .. 9, hl.dsp.exec_cmd("~/.config/hypr/scripts/wsaction.sh workspace 9"))
    hl.bind("SUPER" .. " + " .. 0, hl.dsp.exec_cmd("~/.config/hypr/scripts/wsaction.sh workspace 10"))
    -- Go to workspace group #
    hl.bind("CTRL+SUPER" .. " + " .. 1, hl.dsp.exec_cmd("~/.config/hypr/scripts/wsaction.sh -g workspace 1"))
    hl.bind("CTRL+SUPER" .. " + " .. 2, hl.dsp.exec_cmd("~/.config/hypr/scripts/wsaction.sh -g workspace 2"))
    hl.bind("CTRL+SUPER" .. " + " .. 3, hl.dsp.exec_cmd("~/.config/hypr/scripts/wsaction.sh -g workspace 3"))
    hl.bind("CTRL+SUPER" .. " + " .. 4, hl.dsp.exec_cmd("~/.config/hypr/scripts/wsaction.sh -g workspace 4"))
    hl.bind("CTRL+SUPER" .. " + " .. 5, hl.dsp.exec_cmd("~/.config/hypr/scripts/wsaction.sh -g workspace 5"))
    hl.bind("CTRL+SUPER" .. " + " .. 6, hl.dsp.exec_cmd("~/.config/hypr/scripts/wsaction.sh -g workspace 6"))
    hl.bind("CTRL+SUPER" .. " + " .. 7, hl.dsp.exec_cmd("~/.config/hypr/scripts/wsaction.sh -g workspace 7"))
    hl.bind("CTRL+SUPER" .. " + " .. 8, hl.dsp.exec_cmd("~/.config/hypr/scripts/wsaction.sh -g workspace 8"))
    hl.bind("CTRL+SUPER" .. " + " .. 9, hl.dsp.exec_cmd("~/.config/hypr/scripts/wsaction.sh -g workspace 9"))
    hl.bind("CTRL+SUPER" .. " + " .. 0, hl.dsp.exec_cmd("~/.config/hypr/scripts/wsaction.sh -g workspace 10"))
    -- Go to workspace -1/+1 (Moved to reset submap at bottom of file due to Hyprland named submap bug)
    -- Screen zoom reset (defined in global submap for reliability)
    hl.bind("SUPER" .. " + " .. "Escape", hl.dsp.exec_cmd("/home/jesdev12u/.config/hypr/scripts/zoom.sh reset"))
    hl.bind("SUPER+SHIFT" .. " + " .. "Z", hl.dsp.exec_cmd("/home/jesdev12u/.config/hypr/scripts/zoom.sh reset"))
    hl.bind("CTRL+SUPER" .. " + " .. "left", hl.dsp.focus({ workspace = -1 }))
    hl.bind("CTRL+SUPER" .. " + " .. "right", hl.dsp.focus({ workspace = "+1" }))
    hl.bind("SUPER" .. " + " .. "Page_Up", hl.dsp.focus({ workspace = -1 }))
    hl.bind("SUPER" .. " + " .. "Page_Down", hl.dsp.focus({ workspace = "+1" }))
    -- Go to workspace group -1/+1
    hl.bind("CTRL+SUPER" .. " + " .. "mouse_down", hl.dsp.focus({ workspace = -10 }))
    hl.bind("CTRL+SUPER" .. " + " .. "mouse_up", hl.dsp.focus({ workspace = "+10" }))
    -- Toggle special workspace
    hl.bind("SUPER" .. " + " .. "S", hl.dsp.exec_cmd("caelestia toggle specialws"))
    -- Move window to workspace #
    hl.bind("SUPER+ALT" .. " + " .. 1, hl.dsp.exec_cmd("~/.config/hypr/scripts/wsaction.sh movetoworkspace 1"))
    hl.bind("SUPER+ALT" .. " + " .. 2, hl.dsp.exec_cmd("~/.config/hypr/scripts/wsaction.sh movetoworkspace 2"))
    hl.bind("SUPER+ALT" .. " + " .. 3, hl.dsp.exec_cmd("~/.config/hypr/scripts/wsaction.sh movetoworkspace 3"))
    hl.bind("SUPER+ALT" .. " + " .. 4, hl.dsp.exec_cmd("~/.config/hypr/scripts/wsaction.sh movetoworkspace 4"))
    hl.bind("SUPER+ALT" .. " + " .. 5, hl.dsp.exec_cmd("~/.config/hypr/scripts/wsaction.sh movetoworkspace 5"))
    hl.bind("SUPER+ALT" .. " + " .. 6, hl.dsp.exec_cmd("~/.config/hypr/scripts/wsaction.sh movetoworkspace 6"))
    hl.bind("SUPER+ALT" .. " + " .. 7, hl.dsp.exec_cmd("~/.config/hypr/scripts/wsaction.sh movetoworkspace 7"))
    hl.bind("SUPER+ALT" .. " + " .. 8, hl.dsp.exec_cmd("~/.config/hypr/scripts/wsaction.sh movetoworkspace 8"))
    hl.bind("SUPER+ALT" .. " + " .. 9, hl.dsp.exec_cmd("~/.config/hypr/scripts/wsaction.sh movetoworkspace 9"))
    hl.bind("SUPER+ALT" .. " + " .. 0, hl.dsp.exec_cmd("~/.config/hypr/scripts/wsaction.sh movetoworkspace 10"))
    -- Move window to workspace group #
    hl.bind("CTRL+SUPER+ALT" .. " + " .. 1, hl.dsp.exec_cmd("~/.config/hypr/scripts/wsaction.sh -g movetoworkspace 1"))
    hl.bind("CTRL+SUPER+ALT" .. " + " .. 2, hl.dsp.exec_cmd("~/.config/hypr/scripts/wsaction.sh -g movetoworkspace 2"))
    hl.bind("CTRL+SUPER+ALT" .. " + " .. 3, hl.dsp.exec_cmd("~/.config/hypr/scripts/wsaction.sh -g movetoworkspace 3"))
    hl.bind("CTRL+SUPER+ALT" .. " + " .. 4, hl.dsp.exec_cmd("~/.config/hypr/scripts/wsaction.sh -g movetoworkspace 4"))
    hl.bind("CTRL+SUPER+ALT" .. " + " .. 5, hl.dsp.exec_cmd("~/.config/hypr/scripts/wsaction.sh -g movetoworkspace 5"))
    hl.bind("CTRL+SUPER+ALT" .. " + " .. 6, hl.dsp.exec_cmd("~/.config/hypr/scripts/wsaction.sh -g movetoworkspace 6"))
    hl.bind("CTRL+SUPER+ALT" .. " + " .. 7, hl.dsp.exec_cmd("~/.config/hypr/scripts/wsaction.sh -g movetoworkspace 7"))
    hl.bind("CTRL+SUPER+ALT" .. " + " .. 8, hl.dsp.exec_cmd("~/.config/hypr/scripts/wsaction.sh -g movetoworkspace 8"))
    hl.bind("CTRL+SUPER+ALT" .. " + " .. 9, hl.dsp.exec_cmd("~/.config/hypr/scripts/wsaction.sh -g movetoworkspace 9"))
    hl.bind("CTRL+SUPER+ALT" .. " + " .. 0, hl.dsp.exec_cmd("~/.config/hypr/scripts/wsaction.sh -g movetoworkspace 10"))
    -- Move window to workspace -1/+1
    hl.bind("SUPER+ALT" .. " + " .. "Page_Up", hl.dsp.window.move({ workspace = -1 }))
    hl.bind("SUPER+ALT" .. " + " .. "Page_Down", hl.dsp.window.move({ workspace = "+1" }))
    hl.bind("SUPER+ALT" .. " + " .. "mouse_down", hl.dsp.window.move({ workspace = -1 }))
    hl.bind("SUPER+ALT" .. " + " .. "mouse_up", hl.dsp.window.move({ workspace = "+1" }))
    hl.bind("CTRL+SUPER+SHIFT" .. " + " .. "right", hl.dsp.window.move({ workspace = "+1" }))
    hl.bind("CTRL+SUPER+SHIFT" .. " + " .. "left", hl.dsp.window.move({ workspace = -1 }))
    -- Move window to/from special workspace
    hl.bind("CTRL+SUPER+SHIFT" .. " + " .. "up", hl.dsp.window.move({ workspace = "special:special" }))
    hl.bind("CTRL+SUPER+SHIFT" .. " + " .. "down", hl.dsp.window.move({ workspace = "e+0" }))
    hl.bind("SUPER+ALT" .. " + " .. "S", hl.dsp.window.move({ workspace = "special:special" }))
    -- Window groups
    hl.bind("ALT" .. " + " .. "Tab", hl.dsp.window.cycle_next())
    hl.bind("SHIFT+ALT" .. " + " .. "Tab", hl.dsp.window.cycle_next({ next = false }))
    hl.bind("CTRL+ALT" .. " + " .. "Tab", hl.dsp.group.next())
    hl.bind("CTRL+SHIFT+ALT" .. " + " .. "Tab", hl.dsp.group.next({ forward = false }))
    hl.bind("SUPER" .. " + " .. "Comma", hl.dsp.group.toggle())
    hl.bind("SUPER" .. " + " .. "U", hl.dsp.window.move({ out_of_group = true }))
    -- TODO: manual review (unknown dispatcher: lockactivegroup)
    -- hl.bind("Super+Shift + Comma", hl.dsp.lockactivegroup("toggle"))
    -- Window actions
    hl.bind("SUPER" .. " + " .. "left", hl.dsp.focus({ direction = "left" }))
    hl.bind("SUPER" .. " + " .. "right", hl.dsp.focus({ direction = "right" }))
    hl.bind("SUPER" .. " + " .. "up", hl.dsp.focus({ direction = "up" }))
    hl.bind("SUPER" .. " + " .. "down", hl.dsp.focus({ direction = "down" }))
    hl.bind("SUPER+SHIFT" .. " + " .. "left", hl.dsp.window.move({ direction = "left" }))
    hl.bind("SUPER+SHIFT" .. " + " .. "right", hl.dsp.window.move({ direction = "right" }))
    hl.bind("SUPER+SHIFT" .. " + " .. "up", hl.dsp.window.move({ direction = "up" }))
    hl.bind("SUPER+SHIFT" .. " + " .. "down", hl.dsp.window.move({ direction = "down" }))
    -- TODO: manual review (unknown dispatcher: resizeactive)
    -- hl.bind("Super + Minus", hl.dsp.resizeactive("-10% 0"))
    -- Resize left
    -- TODO: manual review (unknown dispatcher: resizeactive)
    -- hl.bind("Super + Equal", hl.dsp.resizeactive("10% 0"))
    -- Resize right
    -- TODO: manual review (unknown dispatcher: resizeactive)
    -- hl.bind("Super+Shift + Minus", hl.dsp.resizeactive("0 -10%"))
    -- Resize up
    -- TODO: manual review (unknown dispatcher: resizeactive)
    -- hl.bind("Super+Shift + Equal", hl.dsp.resizeactive("0 10%"))
    -- Resize down
    -- TODO: manual review (unknown dispatcher: resizeactive)
    -- hl.bind("Super+Alt + left", hl.dsp.resizeactive("-10% 0"))
    -- TODO: manual review (unknown dispatcher: resizeactive)
    -- hl.bind("Super+Alt + right", hl.dsp.resizeactive("10% 0"))
    -- TODO: manual review (unknown dispatcher: resizeactive)
    -- hl.bind("Super+Alt + up", hl.dsp.resizeactive("0 -10%"))
    -- TODO: manual review (unknown dispatcher: resizeactive)
    -- hl.bind("Super+Alt + down", hl.dsp.resizeactive("0 10%"))
    hl.bind("CTRL+SUPER" .. " + " .. "Backslash", hl.dsp.window.center())
    -- TODO: manual review (unknown dispatcher: resizeactive)
    -- hl.bind("Ctrl+Super+Alt + Backslash", hl.dsp.resizeactive("exact 55% 70%"))
    hl.bind("CTRL+SUPER+ALT" .. " + " .. "Backslash", hl.dsp.window.center())
    hl.bind("SUPER+ALT" .. " + " .. "Backslash", hl.dsp.exec_cmd("caelestia resizer pip"))
    -- Move window to picture-in-picture mode
    hl.bind("SUPER" .. " + " .. "P", hl.dsp.window.pin())
    hl.bind("SUPER" .. " + " .. "F", hl.dsp.window.fullscreen())
    hl.bind("SUPER+ALT" .. " + " .. "F", hl.dsp.window.fullscreen())
    -- Fullscreen with borders
    hl.bind("SUPER+ALT" .. " + " .. "Space", hl.dsp.window.float())
    hl.bind("SUPER" .. " + " .. "Q", hl.dsp.window.close())
    -- Special workspace toggles
    hl.bind("CTRL+SHIFT" .. " + " .. "Escape", hl.dsp.exec_cmd("caelestia toggle sysmon"))
    hl.bind("SUPER" .. " + " .. "M", hl.dsp.exec_cmd("caelestia toggle music"))
    hl.bind("SUPER" .. " + " .. "D", hl.dsp.exec_cmd("caelestia toggle communication"))
    hl.bind("SUPER" .. " + " .. "R", hl.dsp.exec_cmd("caelestia toggle todo"))
    -- Apps
    hl.bind("SUPER" .. " + " .. "T", hl.dsp.exec_cmd("app2unit -- " .. terminal))
    hl.bind("SUPER" .. " + " .. "B", hl.dsp.exec_cmd("app2unit -- " .. browser))
    hl.bind("SUPER" .. " + " .. "C", hl.dsp.exec_cmd("app2unit -- " .. editor))
    hl.bind("SUPER" .. " + " .. "E", hl.dsp.exec_cmd("app2unit -- " .. fileExplorer))
    hl.bind("SUPER+ALT" .. " + " .. "E", hl.dsp.exec_cmd("app2unit -- nemo"))
    hl.bind("CTRL+ALT" .. " + " .. "Escape", hl.dsp.exec_cmd("app2unit -- qps"))
    hl.bind("CTRL+ALT" .. " + " .. "V", hl.dsp.exec_cmd("app2unit -- pavucontrol"))
    -- Utilities
    hl.bind("Print", hl.dsp.exec_cmd("caelestia screenshot"), { locked = true })
    -- Full screen capture > clipboard
    hl.bind("SUPER+SHIFT" .. " + " .. "S", hl.dsp.global("caelestia:screenshotFreeze"))
    -- Capture region (freeze)
    hl.bind("SUPER+SHIFT+ALT" .. " + " .. "S", hl.dsp.global("caelestia:screenshot"))
    -- Capture region
    hl.bind("SUPER+ALT" .. " + " .. "R", hl.dsp.exec_cmd("caelestia record -s"))
    -- Record screen with sound
    hl.bind("CTRL+ALT" .. " + " .. "R", hl.dsp.exec_cmd("caelestia record"))
    -- Record screen
    hl.bind("SUPER+SHIFT+ALT" .. " + " .. "R", hl.dsp.exec_cmd("caelestia record -r"))
    -- Record region
    hl.bind("SUPER+SHIFT" .. " + " .. "C", hl.dsp.exec_cmd("hyprpicker -a"))
    -- Colour picker
    hl.bind("SUPER" .. " + " .. "H", hl.dsp.exec_cmd("/home/jesdev12u/.config/hypr/scripts/toggle_keybinds_help.sh"))
    -- Volume
    hl.bind("XF86AudioMicMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"), { locked = true })
    hl.bind("XF86AudioMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"), { locked = true })
    hl.bind("SUPER+SHIFT" .. " + " .. "M", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"), { locked = true })
    hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ 0; wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ " .. volumeStep .. "%+"), { locked = true })
    hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ 0; wpctl set-volume @DEFAULT_AUDIO_SINK@ " .. volumeStep .. "%-"), { locked = true })
    hl.bind("CTRL+SHIFT+SUPER" .. " + " .. "bracketright", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ 0; wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ " .. volumeStep .. "%+"), { locked = true })
    hl.bind("CTRL+SHIFT+SUPER" .. " + " .. "braceright", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ 0; wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ " .. volumeStep .. "%+"), { locked = true })
    hl.bind("CTRL+SHIFT+SUPER" .. " + " .. "code:35", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ 0; wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ " .. volumeStep .. "%+"), { locked = true })
    hl.bind("CTRL+SHIFT+SUPER" .. " + " .. "slash", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ 0; wpctl set-volume @DEFAULT_AUDIO_SINK@ " .. volumeStep .. "%-"), { locked = true })
    hl.bind("CTRL+SHIFT+SUPER" .. " + " .. "question", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ 0; wpctl set-volume @DEFAULT_AUDIO_SINK@ " .. volumeStep .. "%-"), { locked = true })
    hl.bind("CTRL+SHIFT+SUPER" .. " + " .. "code:61", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ 0; wpctl set-volume @DEFAULT_AUDIO_SINK@ " .. volumeStep .. "%-"), { locked = true })
    -- Sleep
    hl.bind("SUPER+SHIFT" .. " + " .. "L", hl.dsp.exec_cmd("systemctl suspend-then-hibernate"), { locked = true })
    -- Clipboard and emoji picker
    hl.bind("SUPER" .. " + " .. "V", hl.dsp.exec_cmd("pkill fuzzel || " .. hypr .. "/scripts/clipboard.py"))
    hl.bind("SUPER+ALT" .. " + " .. "V", hl.dsp.exec_cmd("pkill fuzzel || " .. hypr .. "/scripts/clipboard.py -d"))
    hl.bind("SUPER" .. " + " .. "Period", hl.dsp.exec_cmd("pkill fuzzel || caelestia emoji -p"))
    hl.bind("CTRL+SHIFT+ALT" .. " + " .. "V", hl.dsp.exec_cmd("sleep 0.5s && ydotool type -d 1 $(cliphist list | head -1 | cliphist decode)"), { locked = true })
    -- Alternate paste
    -- Testing
    hl.bind("SUPER+ALT" .. " + " .. "f12", hl.dsp.exec_cmd("notify-send -u low -i dialog-information-symbolic 'Test notification' Here's a really long message to test truncation and wrapping\\nYou can middle click or flick this notification to dismiss it! -a 'Shell' -A Test1=I got it! -A Test2=Another action"), { locked = true })
end)


-- Mouse binds (global)

hl.bind("SUPER" .. " + " .. "mouse:272", hl.dsp.global("caelestia:launcherInterrupt"), { non_consuming = true })

hl.bind("SUPER" .. " + " .. "mouse:273", hl.dsp.global("caelestia:launcherInterrupt"), { non_consuming = true })

hl.bind("SUPER" .. " + " .. "mouse:272", hl.dsp.window.drag(), { mouse = true })

hl.bind("SUPER" .. " + " .. "Z", hl.dsp.window.drag(), { mouse = true })

hl.bind("SUPER" .. " + " .. "mouse:273", hl.dsp.window.resize(), { mouse = true })

hl.bind("SUPER" .. " + " .. "X", hl.dsp.window.resize(), { mouse = true })

-- Screen zoom (fluid like macOS) - Defined under reset submap to work around Hyprland named submap bug

hl.bind("SUPER" .. " + " .. "mouse_up", hl.dsp.exec_cmd("/home/jesdev12u/.config/hypr/scripts/zoom.sh out"))

hl.bind("SUPER" .. " + " .. "mouse_down", hl.dsp.exec_cmd("/home/jesdev12u/.config/hypr/scripts/zoom.sh in"))

-- Workspace switching (restored to Super+Shift)

-- Send launcher interrupt on Super+Shift+Scroll to prevent launcher from opening on release

hl.bind("SUPER+SHIFT" .. " + " .. "mouse_down", hl.dsp.global("caelestia:launcherInterrupt"), { ignore_mods = true, non_consuming = true })

hl.bind("SUPER+SHIFT" .. " + " .. "mouse_up", hl.dsp.global("caelestia:launcherInterrupt"), { ignore_mods = true, non_consuming = true })

hl.bind("SUPER+SHIFT" .. " + " .. "mouse_down", hl.dsp.focus({ workspace = -1 }))

hl.bind("SUPER+SHIFT" .. " + " .. "mouse_up", hl.dsp.focus({ workspace = "+1" }))

-- Exec (run every reload)
hl.on("config.reloaded", function()
    hl.dispatch(hl.dsp.submap("global"))
end)

hl.on("hyprland.start", function()
    hl.dispatch(hl.dsp.submap("global"))
end)
