-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- ######## Window rules ########

hl.window_rule({
    name  = "opacity__windowopaci",
    match = {
        fullscreen = false,
    },
    opacity = windowOpacity .. " override",
})

hl.window_rule({
    name  = "opaque_true",
    match = {
        class = "foot|equibop|org\\.quickshell|imv|swappy",
    },
    opaque = true,
})

-- They use native transparency or we want them opaque

hl.window_rule({
    name  = "center_true",
    match = {
        float = true,
        xwayland = false,
    },
    center = true,
})

-- Center all floating windows (not xwayland cause popups)

-- Float

hl.window_rule({
    name  = "float_true",
    match = {
        class = "guifetch",
    },
    float = true,
})

-- FlafyDev/guifetch

hl.window_rule({
    name  = "float_true",
    match = {
        class = "yad",
    },
    float = true,
})

hl.window_rule({
    name  = "float_true",
    match = {
        class = "zenity",
    },
    float = true,
})

hl.window_rule({
    name  = "float_true",
    match = {
        class = "wev",
    },
    float = true,
})

hl.window_rule({
    name  = "float_true",
    match = {
        class = "org\\.gnome\\.FileRoller",
    },
    float = true,
})

hl.window_rule({
    name  = "float_true",
    match = {
        class = "file-roller",
    },
    float = true,
})

-- WHY IS THERE TWOOOOOOOOOOOOOOOO

hl.window_rule({
    name  = "float_true",
    match = {
        class = "blueman-manager",
    },
    float = true,
})

hl.window_rule({
    name  = "float_true",
    match = {
        class = "com\\.github\\.GradienceTeam\\.Gradience",
    },
    float = true,
})

hl.window_rule({
    name  = "float_true",
    match = {
        class = "feh",
    },
    float = true,
})

hl.window_rule({
    name  = "float_true",
    match = {
        class = "imv",
    },
    float = true,
})

hl.window_rule({
    name  = "float_true",
    match = {
        class = "system-config-printer",
    },
    float = true,
})

hl.window_rule({
    name  = "float_true",
    match = {
        class = "org\\.quickshell",
    },
    float = true,
})

-- Float, resize and center

hl.window_rule({
    name  = "float_true",
    match = {
        class = "foot",
        title = "nmtui",
    },
    float = true,
})

hl.window_rule({
    name  = "size_60__70_",
    match = {
        class = "foot",
        title = "nmtui",
    },
    size = "60% 70%",
})

hl.window_rule({
    name  = "center_1",
    match = {
        class = "foot",
        title = "nmtui",
    },
    center = 1,
})

hl.window_rule({
    name  = "float_true",
    match = {
        class = "org\\.gnome\\.Settings",
    },
    float = true,
})

hl.window_rule({
    name  = "size_70__80_",
    match = {
        class = "org\\.gnome\\.Settings",
    },
    size = "70% 80%",
})

hl.window_rule({
    name  = "center_1",
    match = {
        class = "org\\.gnome\\.Settings",
    },
    center = 1,
})

hl.window_rule({
    name  = "float_true",
    match = {
        class = "org\\.pulseaudio\\.pavucontrol|yad-icon-browser",
    },
    float = true,
})

hl.window_rule({
    name  = "size_60__70_",
    match = {
        class = "org\\.pulseaudio\\.pavucontrol|yad-icon-browser",
    },
    size = "60% 70%",
})

hl.window_rule({
    name  = "center_1",
    match = {
        class = "org\\.pulseaudio\\.pavucontrol|yad-icon-browser",
    },
    center = 1,
})

hl.window_rule({
    name  = "float_true",
    match = {
        class = "nwg-look",
    },
    float = true,
})

hl.window_rule({
    name  = "size_50__60_",
    match = {
        class = "nwg-look",
    },
    size = "50% 60%",
})

hl.window_rule({
    name  = "center_1",
    match = {
        class = "nwg-look",
    },
    center = 1,
})

-- Keybinds glossary floating window

hl.window_rule({
    name  = "float_true",
    match = {
        title = "Glosario de Keybinds",
    },
    float = true,
})

hl.window_rule({
    name  = "size_800_600",
    match = {
        title = "Glosario de Keybinds",
    },
    size = "800 600",
})

hl.window_rule({
    name  = "center_1",
    match = {
        title = "Glosario de Keybinds",
    },
    center = 1,
})

-- Special workspaces

hl.window_rule({
    name  = "workspace_special_sy",
    match = {
        class = "btop",
    },
    workspace = "special:sysmon",
})

hl.window_rule({
    name  = "workspace_special_mu",
    match = {
        class = "feishin|Spotify|Supersonic|Cider|com.github.th_ch.youtube_music|Plexamp|com-maxrave-simpmusic-MainKt",
    },
    workspace = "special:music",
})

hl.window_rule({
    name  = "workspace_special_mu",
    match = {
        initial_title = "Spotify( Free)?",
    },
    workspace = "special:music",
})

-- Spotify wayland, it has no class for some reason

hl.window_rule({
    name  = "workspace_special_co",
    match = {
        class = "discord|equibop|vesktop|whatsapp",
    },
    workspace = "special:communication",
})

hl.window_rule({
    name  = "workspace_special_to",
    match = {
        class = "Todoist",
    },
    workspace = "special:todo",
})

-- Dialogs

hl.window_rule({
    name  = "float_true",
    match = {
        title = "(Select|Open)( a)? (File|Folder)(s)?",
    },
    float = true,
})

hl.window_rule({
    name  = "float_true",
    match = {
        title = "File (Operation|Upload)( Progress)?",
    },
    float = true,
})

hl.window_rule({
    name  = "float_true",
    match = {
        title = ".* Properties",
    },
    float = true,
})

hl.window_rule({
    name  = "float_true",
    match = {
        title = "Export Image as PNG",
    },
    float = true,
})

hl.window_rule({
    name  = "float_true",
    match = {
        title = "GIMP Crash Debug",
    },
    float = true,
})

hl.window_rule({
    name  = "float_true",
    match = {
        title = "Save As",
    },
    float = true,
})

hl.window_rule({
    name  = "float_true",
    match = {
        title = "Library",
    },
    float = true,
})

-- Picture in picture (resize and move done via script)

hl.window_rule({
    name  = "move_100_-w-2__100_-",
    match = {
        title = "Picture(-| )in(-| )[Pp]icture",
    },
    move = "100%-w-2% 100%-w-3%",
})

-- Initial move so window doesn't shoot across the screen from the center

hl.window_rule({
    name  = "keep_aspect_ratio_tr",
    match = {
        title = "Picture(-| )in(-| )[Pp]icture",
    },
    -- TODO: review rule: "keep_aspect_ratio true"
})

hl.window_rule({
    name  = "float_true",
    match = {
        title = "Picture(-| )in(-| )[Pp]icture",
    },
    float = true,
})

hl.window_rule({
    name  = "pin_true",
    match = {
        title = "Picture(-| )in(-| )[Pp]icture",
    },
    pin = true,
})

-- Creative software

hl.window_rule({
    name  = "opaque_true",
    match = {
        class = "krita|gimp|inkscape|darktable|resolve|kdenlive|shotcut|blender|godot",
    },
    opaque = true,
})

-- Ueberzugpp

hl.window_rule({
    name  = "float_true",
    match = {
        class = "^(ueberzugpp_.*)$",
    },
    float = true,
})

hl.window_rule({
    name  = "no_initial_focus_tru",
    match = {
        class = "^(ueberzugpp_.*)$",
    },
    -- TODO: review rule: "no_initial_focus true"
})

-- Steam

hl.window_rule({
    name  = "rounding_10",
    match = {
        class = "steam",
    },
    rounding = 10,
})

hl.window_rule({
    name  = "float_true",
    match = {
        title = "Friends List",
        class = "steam",
    },
    float = true,
})

-- Games (Steam, Lutris/Wine, Gamescope)

hl.window_rule({
    name  = "opaque_true",
    match = {
        class = "(steam_app_(default|[0-9]+))|gamescope",
    },
    opaque = true,
})

hl.window_rule({
    name  = "immediate_true",
    match = {
        class = "(steam_app_(default|[0-9]+))|gamescope",
    },
    -- TODO: review rule: "immediate true"
})

-- Allow tearing for games

hl.window_rule({
    name  = "idle_inhibit_always",
    match = {
        class = "(steam_app_(default|[0-9]+))|gamescope",
    },
    -- TODO: review rule: "idle_inhibit always"
})

-- Always idle inhibit when playing a game

-- Minecraft launcher consoles

hl.window_rule({
    name  = "float_true",
    match = {
        class = "com-atlauncher-App",
        title = "ATLauncher Console",
    },
    float = true,
})

hl.window_rule({
    name  = "float_true",
    match = {
        class = "PandoraLauncher",
        title = "Minecraft Game Output",
    },
    float = true,
})

-- Autodesk Fusion 360

hl.window_rule({
    name  = "no_blur_true",
    match = {
        title = "Fusion360|(Marking Menu)",
        class = "fusion360\\.exe",
    },
    -- TODO: review rule: "no_blur true"
})

-- Ugh xwayland popups

hl.window_rule({
    name  = "no_dim_true",
    match = {
        xwayland = 1,
        title = "win[0-9]+",
    },
    -- TODO: review rule: "no_dim true"
})

hl.window_rule({
    name  = "no_shadow_true",
    match = {
        xwayland = 1,
        title = "win[0-9]+",
    },
    -- TODO: review rule: "no_shadow true"
})

hl.window_rule({
    name  = "rounding_10",
    match = {
        xwayland = 1,
        title = "win[0-9]+",
    },
    rounding = 10,
})

-- ######## Workspace rules ########

hl.workspace_rule({
    workspace = "w[tv1]s[false]",
    gaps_out = singleWindowGapsOut,
})

hl.workspace_rule({
    workspace = "f[1]s[false]",
    gaps_out = singleWindowGapsOut,
})

-- ######## Layer rules ########

hl.layer_rule({
    match = {
        namespace = "match:namespace hyprpicker",
    },
    animation = "fade",
})

-- Colour picker out animation

hl.layer_rule({
    match = {
        namespace = "match:namespace logout_dialog",
    },
    animation = "fade",
})

-- wlogout

hl.layer_rule({
    match = {
        namespace = "match:namespace selection",
    },
    animation = "fade",
})

-- slurp

hl.layer_rule({
    match = {
        namespace = "match:namespace wayfreeze",
    },
    animation = "fade",
})

-- Fuzzel

hl.layer_rule({
    match = {
        namespace = "match:namespace launcher",
    },
    animation = "popin 80%",
})

hl.layer_rule({
    match = {
        namespace = "match:namespace launcher",
    },
    blur = true,
})

-- Shell

hl.layer_rule({
    match = {
        namespace = "match:namespace caelestia-(border-exclusion|area-picker)",
    },
    no_anim = true,
})

hl.layer_rule({
    match = {
        namespace = "match:namespace caelestia-(drawers|background)",
    },
    animation = "fade",
})
