-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

hl.config({
    scrolling = {
        fullscreen_on_one_column = true,
        focus_fit_method = 1,
        column_width = 0.5,
        follow_focus = true,
        follow_min_visible = 0.0,
        explicit_column_widths = { 0.35, 0.5, 0.65, 1.0 },
    },
})
